# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               ds.co.tt
url:                 http://ds.co.tt
baseurl:             ''

# About/contact
author:
  name:              Dylan Scott
  url:               http://ds.co.tt
  email:             dylan.scott@gmail.com

# Custom vars
version:             1.0.0
